# 01. EDA

In [23]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', 500)

In [20]:
train = pd.read_csv("./data/train.csv")
train.drop_duplicates(subset=train.columns.tolist()[5:20], inplace=True, ignore_index=True)
test = pd.read_csv("./data/test.csv")

train2 = pd.concat([pd.get_dummies(train.iloc[:, 5:20]), train['class']], axis=1)
test2 = pd.get_dummies(test.iloc[:, 5:20])

train2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 256 entries, 0 to 255
Data columns (total 46 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SNP_01_A A  256 non-null    uint8
 1   SNP_01_A G  256 non-null    uint8
 2   SNP_01_G G  256 non-null    uint8
 3   SNP_02_A A  256 non-null    uint8
 4   SNP_02_A G  256 non-null    uint8
 5   SNP_02_G G  256 non-null    uint8
 6   SNP_03_A A  256 non-null    uint8
 7   SNP_03_C A  256 non-null    uint8
 8   SNP_03_C C  256 non-null    uint8
 9   SNP_04_A A  256 non-null    uint8
 10  SNP_04_G A  256 non-null    uint8
 11  SNP_04_G G  256 non-null    uint8
 12  SNP_05_A A  256 non-null    uint8
 13  SNP_05_C A  256 non-null    uint8
 14  SNP_05_C C  256 non-null    uint8
 15  SNP_06_A A  256 non-null    uint8
 16  SNP_06_A G  256 non-null    uint8
 17  SNP_06_G G  256 non-null    uint8
 18  SNP_07_A A  256 non-null    uint8
 19  SNP_07_G A  256 non-null    uint8
 20  SNP_07_G G  256 non-null    uint8
 21  SNP_08_A A  256 non-null    uint8
 22  SNP_08_G A  256 non-null    uint8
 23  SNP_08_G G  256 non-null    uint8
 24  SNP_09_A A  256 non-null    uint8
 25  SNP_09_G A  256 non-null    uint8
 26  SNP_09_G G  256 non-null    uint8
 27  SNP_10_A A  256 non-null    uint8
 28  SNP_10_A G  256 non-null    uint8
 29  SNP_10_G G  256 non-null    uint8
 30  SNP_11_A A  256 non-null    uint8
 31  SNP_11_A G  256 non-null    uint8
 32  SNP_11_G G  256 non-null    uint8
 33  SNP_12_A A  256 non-null    uint8
 34  SNP_12_G A  256 non-null    uint8
 35  SNP_12_G G  256 non-null    uint8
 36  SNP_13_A A  256 non-null    uint8
 37  SNP_13_A G  256 non-null    uint8
 38  SNP_13_G G  256 non-null    uint8
 39  SNP_14_A A  256 non-null    uint8
 40  SNP_14_C A  256 non-null    uint8
 41  SNP_14_C C  256 non-null    uint8
 42  SNP_15_A A  256 non-null    uint8
 43  SNP_15_G A  256 non-null    uint8
 44  SNP_15_G G  256 non-null    uint8
 45  class       256 non-null    object
dtypes: object(1), uint8(45)
memory usage: 13.4+ KB

In [21]:
test2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175 entries, 0 to 174
Data columns (total 45 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SNP_01_A A  175 non-null    uint8
 1   SNP_01_A G  175 non-null    uint8
 2   SNP_01_G G  175 non-null    uint8
 3   SNP_02_A A  175 non-null    uint8
 4   SNP_02_A G  175 non-null    uint8
 5   SNP_02_G G  175 non-null    uint8
 6   SNP_03_A A  175 non-null    uint8
 7   SNP_03_C A  175 non-null    uint8
 8   SNP_03_C C  175 non-null    uint8
 9   SNP_04_A A  175 non-null    uint8
 10  SNP_04_G A  175 non-null    uint8
 11  SNP_04_G G  175 non-null    uint8
 12  SNP_05_A A  175 non-null    uint8
 13  SNP_05_C A  175 non-null    uint8
 14  SNP_05_C C  175 non-null    uint8
 15  SNP_06_A A  175 non-null    uint8
 16  SNP_06_A G  175 non-null    uint8
 17  SNP_06_G G  175 non-null    uint8
 18  SNP_07_A A  175 non-null    uint8
 19  SNP_07_G A  175 non-null    uint8
 20  SNP_07_G G  175 non-null    uint8
 21  SNP_08_A A  175 non-null    uint8
 22  SNP_08_G A  175 non-null    uint8
 23  SNP_08_G G  175 non-null    uint8
 24  SNP_09_A A  175 non-null    uint8
 25  SNP_09_G A  175 non-null    uint8
 26  SNP_09_G G  175 non-null    uint8
 27  SNP_10_A A  175 non-null    uint8
 28  SNP_10_A G  175 non-null    uint8
 29  SNP_10_G G  175 non-null    uint8
 30  SNP_11_A A  175 non-null    uint8
 31  SNP_11_A G  175 non-null    uint8
 32  SNP_11_G G  175 non-null    uint8
 33  SNP_12_A A  175 non-null    uint8
 34  SNP_12_G A  175 non-null    uint8
 35  SNP_12_G G  175 non-null    uint8
 36  SNP_13_A A  175 non-null    uint8
 37  SNP_13_A G  175 non-null    uint8
 38  SNP_13_G G  175 non-null    uint8
 39  SNP_14_A A  175 non-null    uint8
 40  SNP_14_C A  175 non-null    uint8
 41  SNP_14_C C  175 non-null    uint8
 42  SNP_15_A A  175 non-null    uint8
 43  SNP_15_G A  175 non-null    uint8
 44  SNP_15_G G  175 non-null    uint8
dtypes: uint8(45)
memory usage: 7.8 KB

In [24]:
train2.describe()

,SNP_01_A A,SNP_01_A G,SNP_01_G G,SNP_02_A A,SNP_02_A G,SNP_02_G G,SNP_03_A A,SNP_03_C A,SNP_03_C C,SNP_04_A A,SNP_04_G A,SNP_04_G G,SNP_05_A A,SNP_05_C A,SNP_05_C C,SNP_06_A A,SNP_06_A G,SNP_06_G G,SNP_07_A A,SNP_07_G A,SNP_07_G G,SNP_08_A A,SNP_08_G A,SNP_08_G G,SNP_09_A A,SNP_09_G A,SNP_09_G G,SNP_10_A A,SNP_10_A G,SNP_10_G G,SNP_11_A A,SNP_11_A G,SNP_11_G G,SNP_12_A A,SNP_12_G A,SNP_12_G G,SNP_13_A A,SNP_13_A G,SNP_13_G G,SNP_14_A A,SNP_14_C A,SNP_14_C C,SNP_15_A A,SNP_15_G A,SNP_15_G G
count,256.000000,256.000000,256.000000,256.000000,256.000000,256.000000,256.000000,256.000000,256.000000,256.00000,256.000000,256.000000,256.000000,256.000000,256.000000,256.000000,256.000000,256.000000,256.000000,256.000000,256.000000,256.000000,256.000000,256.000000,256.000000,256.000000,256.000000,256.000000,256.000000,256.000000,256.000000,256.000000,256.000000,256.000000,256.00000,256.000000,256.000000,256.000000,256.000000,256.000000,256.000000,256.000000,256.000000,256.000000,256.000000
mean,0.175781,0.277344,0.546875,0.222656,0.378906,0.398438,0.457031,0.355469,0.187500,0.46875,0.355469,0.175781,0.347656,0.335938,0.316406,0.234375,0.476562,0.289062,0.632812,0.187500,0.179688,0.324219,0.371094,0.304688,0.707031,0.210938,0.082031,0.164062,0.250000,0.585938,0.320312,0.371094,0.308594,0.527344,0.28125,0.191406,0.199219,0.371094,0.429688,0.714844,0.199219,0.085938,0.417969,0.378906,0.203125
std,0.381380,0.448565,0.498773,0.416844,0.486065,0.490535,0.499126,0.479593,0.391077,0.50000,0.479593,0.381380,0.477159,0.473242,0.465984,0.424437,0.500429,0.454215,0.482982,0.391077,0.384679,0.468999,0.484044,0.461177,0.456016,0.408773,0.274950,0.371058,0.433861,0.493524,0.467511,0.484044,0.462818,0.500230,0.45049,0.394179,0.400195,0.484044,0.496001,0.452373,0.400195,0.280821,0.494191,0.486065,0.403113
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.00000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.250000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [33]:
train2[train2['SNP_03_C C'] == 0]['class'].value_counts()

B    82
A    64
C    62
Name: class, dtype: int64

In [25]:
train2[train2['class']=='A'].describe()

,SNP_01_A A,SNP_01_A G,SNP_01_G G,SNP_02_A A,SNP_02_A G,SNP_02_G G,SNP_03_A A,SNP_03_C A,SNP_03_C C,SNP_04_A A,SNP_04_G A,SNP_04_G G,SNP_05_A A,SNP_05_C A,SNP_05_C C,SNP_06_A A,SNP_06_A G,SNP_06_G G,SNP_07_A A,SNP_07_G A,SNP_07_G G,SNP_08_A A,SNP_08_G A,SNP_08_G G,SNP_09_A A,SNP_09_G A,SNP_09_G G,SNP_10_A A,SNP_10_A G,SNP_10_G G,SNP_11_A A,SNP_11_A G,SNP_11_G G,SNP_12_A A,SNP_12_G A,SNP_12_G G,SNP_13_A A,SNP_13_A G,SNP_13_G G,SNP_14_A A,SNP_14_C A,SNP_14_C C,SNP_15_A A,SNP_15_G A,SNP_15_G G
count,64.00000,64.000000,64.000000,64.0,64.000000,64.000000,64.0,64.0,64.0,64.000000,64.000000,64.000000,64.000000,64.000000,64.0,64.0,64.000000,64.000000,64.0,64.000000,64.000000,64.000000,64.000000,64.0,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.0,64.000000,64.000000,64.000000,64.000000,64.000000,64.0,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000
mean,0.62500,0.328125,0.046875,0.0,0.093750,0.906250,1.0,0.0,0.0,0.031250,0.468750,0.500000,0.781250,0.218750,0.0,0.0,0.312500,0.687500,0.0,0.281250,0.718750,0.843750,0.156250,0.0,0.203125,0.484375,0.312500,0.484375,0.468750,0.046875,0.0,0.187500,0.812500,0.015625,0.296875,0.687500,0.0,0.046875,0.953125,0.156250,0.531250,0.312500,0.062500,0.296875,0.640625
std,0.48795,0.473242,0.213042,0.0,0.293785,0.293785,0.0,0.0,0.0,0.175368,0.502967,0.503953,0.416667,0.416667,0.0,0.0,0.467177,0.467177,0.0,0.453163,0.453163,0.365963,0.365963,0.0,0.405505,0.503706,0.467177,0.503706,0.502967,0.213042,0.0,0.393398,0.393398,0.125000,0.460493,0.467177,0.0,0.213042,0.213042,0.365963,0.502967,0.467177,0.243975,0.460493,0.483610
min,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,1.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.00000,0.000000,0.000000,0.0,0.000000,1.000000,1.0,0.0,0.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.00000,0.000000,0.000000,0.0,0.000000,1.000000,1.0,0.0,0.0,0.000000,0.000000,0.500000,1.000000,0.000000,0.0,0.0,0.000000,1.000000,0.0,0.000000,1.000000,1.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.0,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
75%,1.00000,1.000000,0.000000,0.0,0.000000,1.000000,1.0,0.0,0.0,0.000000,1.000000,1.000000,1.000000,0.000000,0.0,0.0,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,0.000000,0.0,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.0,0.000000,1.000000,0.000000,1.000000,1.000000,0.0,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000
max,1.00000,1.000000,1.000000,0.0,1.000000,1.000000,1.0,0.0,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [26]:
train2[train2['class']=='B'].describe()

,SNP_01_A A,SNP_01_A G,SNP_01_G G,SNP_02_A A,SNP_02_A G,SNP_02_G G,SNP_03_A A,SNP_03_C A,SNP_03_C C,SNP_04_A A,SNP_04_G A,SNP_04_G G,SNP_05_A A,SNP_05_C A,SNP_05_C C,SNP_06_A A,SNP_06_A G,SNP_06_G G,SNP_07_A A,SNP_07_G A,SNP_07_G G,SNP_08_A A,SNP_08_G A,SNP_08_G G,SNP_09_A A,SNP_09_G A,SNP_09_G G,SNP_10_A A,SNP_10_A G,SNP_10_G G,SNP_11_A A,SNP_11_A G,SNP_11_G G,SNP_12_A A,SNP_12_G A,SNP_12_G G,SNP_13_A A,SNP_13_A G,SNP_13_G G,SNP_14_A A,SNP_14_C A,SNP_14_C C,SNP_15_A A,SNP_15_G A,SNP_15_G G
count,113.0,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,113.0,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,113.0,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,113.000000,113.0,113.0,113.0,113.000000,113.000000,113.000000
mean,0.0,0.221239,0.778761,0.168142,0.513274,0.318584,0.212389,0.513274,0.274336,0.424779,0.460177,0.115044,0.061947,0.309735,0.628319,0.283186,0.539823,0.176991,0.920354,0.079646,0.0,0.070796,0.362832,0.566372,0.796460,0.194690,0.008850,0.0,0.035398,0.964602,0.300885,0.486726,0.212389,0.681416,0.283186,0.035398,0.371681,0.469027,0.159292,1.0,0.0,0.0,0.628319,0.345133,0.026549
std,0.0,0.416930,0.416930,0.375658,0.502050,0.468003,0.410821,0.502050,0.448167,0.496511,0.500632,0.320497,0.242133,0.464444,0.485406,0.452553,0.500632,0.383361,0.271950,0.271950,0.0,0.257627,0.482959,0.497783,0.404424,0.397726,0.094072,0.0,0.185607,0.185607,0.460686,0.502050,0.410821,0.468003,0.452553,0.185607,0.485406,0.501263,0.367578,0.0,0.0,0.0,0.485406,0.477529,0.161476
min,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,0.0,0.0,0.000000,0.000000,0.000000
25%,0.0,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.0,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,0.0,0.0,0.000000,0.000000,0.000000
50%,0.0,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.0,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.0,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,0.0,0.0,1.000000,0.000000,0.000000
75%,0.0,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.0,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.0,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.0,0.0,0.0,1.000000,1.000000,0.000000
max,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,0.0,0.0,1.000000,1.000000,1.000000

In [27]:
train2[train2['class']=='C'].describe()

,SNP_01_A A,SNP_01_A G,SNP_01_G G,SNP_02_A A,SNP_02_A G,SNP_02_G G,SNP_03_A A,SNP_03_C A,SNP_03_C C,SNP_04_A A,SNP_04_G A,SNP_04_G G,SNP_05_A A,SNP_05_C A,SNP_05_C C,SNP_06_A A,SNP_06_A G,SNP_06_G G,SNP_07_A A,SNP_07_G A,SNP_07_G G,SNP_08_A A,SNP_08_G A,SNP_08_G G,SNP_09_A A,SNP_09_G A,SNP_09_G G,SNP_10_A A,SNP_10_A G,SNP_10_G G,SNP_11_A A,SNP_11_A G,SNP_11_G G,SNP_12_A A,SNP_12_G A,SNP_12_G G,SNP_13_A A,SNP_13_A G,SNP_13_G G,SNP_14_A A,SNP_14_C A,SNP_14_C C,SNP_15_A A,SNP_15_G A,SNP_15_G G
count,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.00000,79.000000,79.000000,79.0,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.0,79.000000,79.000000,79.000000,79.000000,79.000000,79.0,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.00000,79.000000,79.000000,79.000000,79.000000
mean,0.063291,0.316456,0.620253,0.481013,0.417722,0.101266,0.367089,0.417722,0.21519,0.886076,0.113924,0.0,0.405063,0.468354,0.126582,0.354430,0.518987,0.126582,0.734177,0.265823,0.0,0.265823,0.556962,0.177215,0.987342,0.012658,0.0,0.139241,0.379747,0.481013,0.607595,0.354430,0.037975,0.721519,0.265823,0.012658,0.113924,0.493671,0.392405,0.759494,0.21519,0.025316,0.405063,0.493671,0.101266
std,0.245042,0.468065,0.488425,0.502832,0.496335,0.303608,0.485091,0.496335,0.41358,0.319749,0.319749,0.0,0.494041,0.502186,0.334629,0.481397,0.502832,0.334629,0.444593,0.444593,0.0,0.444593,0.499919,0.384291,0.112509,0.112509,0.0,0.348409,0.488425,0.502832,0.491406,0.481397,0.192356,0.451116,0.444593,0.112509,0.319749,0.503155,0.491406,0.430122,0.41358,0.158088,0.494041,0.503155,0.303608
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.00000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.0,0.000000,1.000000,0.000000,1.000000,0.000000,0.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.00000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.00000,1.000000,0.000000,0.0,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.0,1.000000,1.000000,0.000000,1.000000,0.000000,0.0,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.00000,0.000000,1.000000,1.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000

In [15]:
test2.describe()

,SNP_01_A A,SNP_01_A G,SNP_01_G G,SNP_02_A A,SNP_02_A G,SNP_02_G G,SNP_03_A A,SNP_03_C A,SNP_03_C C,SNP_04_A A,...,SNP_12_G G,SNP_13_A A,SNP_13_A G,SNP_13_G G,SNP_14_A A,SNP_14_C A,SNP_14_C C,SNP_15_A A,SNP_15_G A,SNP_15_G G
count,175.000000,175.000000,175.000000,175.000000,175.000000,175.000000,175.000000,175.000000,175.000000,175.000000,...,175.000000,175.000000,175.000000,175.000000,175.000000,175.000000,175.000000,175.000000,175.000000,175.000000
mean,0.222857,0.297143,0.480000,0.211429,0.325714,0.462857,0.468571,0.388571,0.142857,0.365714,...,0.194286,0.234286,0.331429,0.434286,0.685714,0.188571,0.125714,0.388571,0.388571,0.222857
std,0.417357,0.458311,0.501033,0.409493,0.469986,0.500049,0.500443,0.488824,0.350931,0.483012,...,0.396785,0.424767,0.472077,0.497085,0.465563,0.392290,0.332478,0.488824,0.488824,0.417357
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,...,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

# BaseModeling

In [36]:
import warnings
warnings.filterwarnings(action='ignore')

import os
import gc
import math
import random
import pickle
import pandas as pd
import numpy as np
import multiprocessing
from tqdm.auto import tqdm

from sklearn.metrics import f1_score

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, TensorDataset, sampler

from xgboost import XGBClassifier, XGBRegressor
from catboost import CatBoostClassifier, CatBoostRegressor
from imblearn.over_sampling import SMOTE, SMOTENC, SMOTEN

import shap
import catboost

In [35]:
train2.iloc[:, :-1] = train2.iloc[:, :-1].astype('category')
test2 = test2.astype('category')
train2.info(), test2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 256 entries, 0 to 255
Data columns (total 46 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SNP_01_A A  256 non-null    category
 1   SNP_01_A G  256 non-null    category
 2   SNP_01_G G  256 non-null    category
 3   SNP_02_A A  256 non-null    category
 4   SNP_02_A G  256 non-null    category
 5   SNP_02_G G  256 non-null    category
 6   SNP_03_A A  256 non-null    category
 7   SNP_03_C A  256 non-null    category
 8   SNP_03_C C  256 non-null    category
 9   SNP_04_A A  256 non-null    category
 10  SNP_04_G A  256 non-null    category
 11  SNP_04_G G  256 non-null    category
 12  SNP_05_A A  256 non-null    category
 13  SNP_05_C A  256 non-null    category
 14  SNP_05_C C  256 non-null    category
 15  SNP_06_A A  256 non-null    category
 16  SNP_06_A G  256 non-null    category
 17  SNP_06_G G  256 non-null    category
 18  SNP_07_A A  256 non-null    category
 19  SNP_07_G A  256 non-null    category
 20  SNP_07_G G  256 non-null    category
 21  SNP_08_A A  256 non-null    category
 22  SNP_08_G A  256 non-null    category
 23  SNP_08_G G  256 non-null    category
 24  SNP_09_A A  256 non-null    category
 25  SNP_09_G A  256 non-null    category
 26  SNP_09_G G  256 non-null    category
 27  SNP_10_A A  256 non-null    category
 28  SNP_10_A G  256 non-null    category
 29  SNP_10_G G  256 non-null    category
 30  SNP_11_A A  256 non-null    category
 31  SNP_11_A G  256 non-null    category
 32  SNP_11_G G  256 non-null    category
 33  SNP_12_A A  256 non-null    category
 34  SNP_12_G A  256 non-null    category
 35  SNP_12_G G  256 non-null    category
 36  SNP_13_A A  256 non-null    category
 37  SNP_13_A G  256 non-null    category
 38  SNP_13_G G  256 non-null    category
 39  SNP_14_A A  256 non-null    category
 40  SNP_14_C A  256 non-null    category
 41  SNP_14_C C  256 non-null    category
 42  SNP_15_A A  256 non-null    category
 43  SNP_15_G A  256 non-null    category
 44  SNP_15_G G  256 non-null    category
 45  class       256 non-null    object
dtypes: category(45), object(1)
memory usage: 18.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175 entries, 0 to 174
Data columns (total 45 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SNP_01_A A  175 non-null    category
 1   SNP_01_A G  175 non-null    category
 2   SNP_01_G G  175 non-null    category
 3   SNP_02_A A  175 non-null    category
 4   SNP_02_A G  175 non-null    category
 5   SNP_02_G G  175 non-null    category
 6   SNP_03_A A  175 non-null    category
 7   SNP_03_C A  175 non-null    category
 8   SNP_03_C C  175 non-null    category
 9   SNP_04_A A  175 non-null    category
 10  SNP_04_G A  175 non-null    category
 11  SNP_04_G G  175 non-null    category
 12  SNP_05_A A  175 non-null    category
 13  SNP_05_C A  175 non-null    category
 14  SNP_05_C C  175 non-null    category
 15  SNP_06_A A  175 non-null    category
 16  SNP_06_A G  175 non-null    category
 17  SNP_06_G G  175 non-null    category
 18  SNP_07_A A  175 non-null    category
 19  SNP_07_G A  175 non-null    category
 20  SNP_07_G G  175 non-null    category
 21  SNP_08_A A  175 non-null    category
 22  SNP_08_G A  175 non-null    category
 23  SNP_08_G G  175 non-null    category
 24  SNP_09_A A  175 non-null    category
 25  SNP_09_G A  175 non-null    category
 26  SNP_09_G G  175 non-null    category
 27  SNP_10_A A  175 non-null    category
 28  SNP_10_A G  175 non-null    category
 29  SNP_10_G G  175 non-null    category
 30  SNP_11_A A  175 non-null    category
 31  SNP_11_A G  175 non-null    category
 32  SNP_11_G G  175 non-null    category
 33  SNP_12_A A  175 non-null    category
 34  SNP_12_G A  175 non-null    category
 35  SNP_12_G G  175 non-null    category
 36  SNP_13_A A  175 non-null    category
 37  SNP_13_A G  175 non-null    category
 38  SNP_13_G G  175 non-null    category
 39  SNP_14_A A  175 non-null    category
 40  SNP_14_C A  175 non-null    category
 41  SNP_14_C C  175 non-null    category
 42  SNP_15_A A  175 non-null    category
 43  SNP_15_G A  175 non-null    category
 44  SNP_15_G G  175 non-null    category
dtypes: category(45)
memory usage: 13.3 KB

(None, None)

In [60]:
from catboost import Pool, cv

def catcv(inputX, inputY, validX, validY, params, cv_count) :  
    
    var_categ = inputX.columns.tolist()
    
    cv_dataset = Pool(data=inputX,
                      label=inputY,
                      cat_features=var_categ)
    
    scores = cv(cv_dataset,
                params,
                fold_count=cv_count,
                stratified=True,
                plot=True)

In [96]:
def catgbmc(inputX, inputY, validX, validY, params) :  
    var_categ = inputX.columns.tolist()
    model = CatBoostClassifier(
        cat_features=var_categ,
        **params,
        task_type='GPU',
        devices='0',
        )
  
    model.fit(
        inputX, inputY,
        eval_set=(inputX, inputY)
        );     

    pred = model.predict(validX)
    score = f1_score(validY, pred, average='macro')
    print(score)
    
    return model

In [89]:
from imblearn.under_sampling import RandomUnderSampler

X, y = train2.iloc[:,:-1], (train2['class']=='A').astype(int)
X_test = test2.copy()

strategy1 = {0:10, 1:10}
strategy2 = {0:1000, 1:1000}

smote1 = RandomUnderSampler(sampling_strategy=strategy1)
smote2 = SMOTEN(sampling_strategy=strategy2, k_neighbors=50)

X1, y1 = smote1.fit_resample(X, y)
X2, y2 = smote2.fit_resample(X, y)

In [90]:
params = {'iterations':300,
          'learning_rate':0.3,
          'l2_leaf_reg' : 10,
          # 'grow_policy' : 'Lossguide',
        #   'auto_class_weights' : 'SqrtBalanced',
          'loss_function' : 'CrossEntropy',
          'eval_metric' : 'F1',
          # 'early_stopping_rounds' : 50,
          'verbose':0,
          'random_seed':0}

In [91]:
catcv(X, y, X, y, params, cv_count=5)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Training on fold [0/5]

bestTest = 1
bestIteration = 1

Training on fold [1/5]

bestTest = 1
bestIteration = 2

Training on fold [2/5]

bestTest = 1
bestIteration = 2

Training on fold [3/5]

bestTest = 1
bestIteration = 3

Training on fold [4/5]

bestTest = 0.9565217391
bestIteration = 1

In [94]:
catcv(X1, y1, X, y, params, cv_count=3)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Training on fold [0/3]

bestTest = 1
bestIteration = 3

Training on fold [1/3]

bestTest = 1
bestIteration = 0

Training on fold [2/3]

bestTest = 0.8
bestIteration = 3

In [95]:
catcv(X2, y2, X, y, params, cv_count=10)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Training on fold [0/10]

bestTest = 1
bestIteration = 1

Training on fold [1/10]

bestTest = 1
bestIteration = 1

Training on fold [2/10]

bestTest = 1
bestIteration = 2

Training on fold [3/10]

bestTest = 1
bestIteration = 5

Training on fold [4/10]

bestTest = 1
bestIteration = 0

Training on fold [5/10]

bestTest = 1
bestIteration = 0

Training on fold [6/10]

bestTest = 0.9950248756
bestIteration = 0

Training on fold [7/10]

bestTest = 1
bestIteration = 1

Training on fold [8/10]

bestTest = 1
bestIteration = 0

Training on fold [9/10]

bestTest = 1
bestIteration = 0

In [97]:
modelA = catgbmc(X2, y2, X, y, params)

1.0

In [99]:
modelA.predict(X_test).sum()

47

## B & not B

In [105]:
from imblearn.under_sampling import RandomUnderSampler

X, y = train2.iloc[:,:-1], (train2['class']=='B').astype(int)
X_test = test2.copy()

strategy1 = {0:30, 1:30}
strategy2 = {0:1000, 1:1000}

smote1 = RandomUnderSampler(sampling_strategy=strategy1)
smote2 = SMOTEN(sampling_strategy=strategy2, k_neighbors=50)

X1, y1 = smote1.fit_resample(X, y)
X2, y2 = smote2.fit_resample(X, y)

In [106]:
params = {'iterations':500,
          'learning_rate':0.03,
          'l2_leaf_reg' : 3,
          # 'grow_policy' : 'Lossguide',
        #   'auto_class_weights' : 'SqrtBalanced',
          'loss_function' : 'CrossEntropy',
          'eval_metric' : 'F1',
          # 'early_stopping_rounds' : 50,
          'verbose':0,
          'random_seed':0}

In [107]:
catcv(X, y, X, y, params, cv_count=5)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Training on fold [0/5]

bestTest = 0.92
bestIteration = 9

Training on fold [1/5]

bestTest = 0.9787234043
bestIteration = 0

Training on fold [2/5]

bestTest = 0.9387755102
bestIteration = 52

Training on fold [3/5]

bestTest = 0.9090909091
bestIteration = 0

Training on fold [4/5]

bestTest = 0.9777777778
bestIteration = 16

In [108]:
catcv(X1, y1, X, y, params, cv_count=3)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Training on fold [0/3]

bestTest = 0.9523809524
bestIteration = 3

Training on fold [1/3]

bestTest = 0.8571428571
bestIteration = 5

Training on fold [2/3]

bestTest = 0.8888888889
bestIteration = 6

In [109]:
catcv(X2, y2, X, y, params, cv_count=10)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Training on fold [0/10]

bestTest = 1
bestIteration = 2

Training on fold [1/10]

bestTest = 1
bestIteration = 9

Training on fold [2/10]

bestTest = 0.9898989899
bestIteration = 277

Training on fold [3/10]

bestTest = 0.9950248756
bestIteration = 2

Training on fold [4/10]

bestTest = 0.9900990099
bestIteration = 19

Training on fold [5/10]

bestTest = 1
bestIteration = 13

Training on fold [6/10]

bestTest = 1
bestIteration = 2

Training on fold [7/10]

bestTest = 0.9852216749
bestIteration = 74

Training on fold [8/10]

bestTest = 0.9850746269
bestIteration = 50

Training on fold [9/10]

bestTest = 1
bestIteration = 7

In [114]:
params = {'iterations':500,
          'learning_rate':0.03,
          'l2_leaf_reg' : 3,
          # 'grow_policy' : 'Lossguide',
        #   'auto_class_weights' : 'SqrtBalanced',
          'loss_function' : 'CrossEntropy',
          'eval_metric' : 'F1',
          # 'early_stopping_rounds' : 50,
          'verbose':0,
          'random_seed':0}

In [115]:
modelB = catgbmc(X2, y2, X, y, params)

1.0

In [116]:
modelB.predict(X_test).sum()

83

## C & not C

In [117]:
X, y = train2.iloc[:,:-1], (train2['class']=='C').astype(int)
X_test = test2.copy()

strategy1 = {0:50, 1:50}
strategy2 = {0:1000, 1:1000}

smote1 = RandomUnderSampler(sampling_strategy=strategy1)
smote2 = SMOTEN(sampling_strategy=strategy2, k_neighbors=50)

X1, y1 = smote1.fit_resample(X, y)
X2, y2 = smote2.fit_resample(X, y)

In [118]:
params = {'iterations':500,
          'learning_rate':0.03,
          'l2_leaf_reg' : 3,
          # 'grow_policy' : 'Lossguide',
        #   'auto_class_weights' : 'SqrtBalanced',
          'loss_function' : 'CrossEntropy',
          'eval_metric' : 'F1',
          # 'early_stopping_rounds' : 50,
          'verbose':0,
          'random_seed':0}

In [119]:
catcv(X, y, X, y, params, cv_count=5)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Training on fold [0/5]

bestTest = 0.8387096774
bestIteration = 60

Training on fold [1/5]

bestTest = 0.9375
bestIteration = 94

Training on fold [2/5]

bestTest = 0.8965517241
bestIteration = 122

Training on fold [3/5]

bestTest = 0.9375
bestIteration = 111

Training on fold [4/5]

bestTest = 0.9677419355
bestIteration = 46

In [120]:
catcv(X1, y1, X, y, params, cv_count=5)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Training on fold [0/5]

bestTest = 1
bestIteration = 26

Training on fold [1/5]

bestTest = 1
bestIteration = 20

Training on fold [2/5]

bestTest = 0.8888888889
bestIteration = 13

Training on fold [3/5]

bestTest = 1
bestIteration = 55

Training on fold [4/5]

bestTest = 0.9
bestIteration = 156

In [122]:
catcv(X2, y2, X, y, params, cv_count=5)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Training on fold [0/5]

bestTest = 0.9975062344
bestIteration = 93

Training on fold [1/5]

bestTest = 0.9874686717
bestIteration = 77

Training on fold [2/5]

bestTest = 0.9924433249
bestIteration = 57

Training on fold [3/5]

bestTest = 0.9898989899
bestIteration = 51

Training on fold [4/5]

bestTest = 0.9925187032
bestIteration = 152

In [123]:
params = {'iterations':500,
          'learning_rate':0.03,
          'l2_leaf_reg' : 3,
          # 'grow_policy' : 'Lossguide',
        #   'auto_class_weights' : 'SqrtBalanced',
          'loss_function' : 'CrossEntropy',
          'eval_metric' : 'F1',
          # 'early_stopping_rounds' : 50,
          'verbose':0,
          'random_seed':0}

In [126]:
modelC = catgbmc(X2, y2, X, y, params)

1.0

In [127]:
modelC.predict(X_test).sum()

39

In [130]:
sample = test[['id']].copy()
sample['class_A'] = modelA.predict_proba(X_test)[:,1]
sample['class_B'] = modelB.predict_proba(X_test)[:,1]
sample['class_C'] = modelC.predict_proba(X_test)[:,1]
sample['total'] = np.argmax(sample[['class_A', 'class_B', 'class_C']].values, axis=1)
sample

           id   class_A   class_B   class_C  total
0    TEST_000  0.764569  0.002600  0.049420      0
1    TEST_001  0.121394  0.998435  0.004510      1
2    TEST_002  0.198651  0.002566  0.994690      2
3    TEST_003  0.125291  0.969023  0.361866      1
4    TEST_004  0.964943  0.001233  0.001203      0
..        ...       ...       ...       ...    ...
170  TEST_170  0.016993  0.940340  0.010600      1
171  TEST_171  0.160463  0.000335  0.998799      2
172  TEST_172  0.160463  0.008046  0.974399      2
173  TEST_173  0.019999  0.998050  0.000795      1
174  TEST_174  0.166349  0.844687  0.006527      1

[175 rows x 5 columns]

In [134]:
sample[(sample.class_A > 0.5) & ((sample.class_B > 0.1) | (sample.class_C > 0.1))]

Empty DataFrame
Columns: [id, class_A, class_B, class_C, total]
Index: []

In [136]:
sample[(sample.class_B > 0.5) & ((sample.class_A > 0.5) | (sample.class_C > 0.5))]

           id   class_A   class_B   class_C  total
119  TEST_119  0.160463  0.714982  0.800611      2

In [137]:
sample[(sample.class_B < 0.5) & (sample.class_A < 0.5) & (sample.class_C < 0.5)]

           id   class_A   class_B   class_C  total
12   TEST_012  0.019494  0.309773  0.264535      1
52   TEST_052  0.362494  0.030795  0.023571      0
60   TEST_060  0.198651  0.007156  0.094667      0
66   TEST_066  0.219316  0.483910  0.052730      1
111  TEST_111  0.166349  0.325725  0.061344      1
139  TEST_139  0.322050  0.013435  0.030233      0
140  TEST_140  0.371136  0.004320  0.024856      0

In [138]:
sample['total'].value_counts()

1    85
0    51
2    39
Name: total, dtype: int64

In [158]:
df = pd.read_csv("submit_high1.csv")
df['class'] = sample['total'].map(lambda x : 'A' if x==0 else ('B' if x==1 else 'C'))
df.to_csv("submit.csv", index=False)
df

           id class
0    TEST_000     A
1    TEST_001     B
2    TEST_002     C
3    TEST_003     B
4    TEST_004     A
..        ...   ...
170  TEST_170     B
171  TEST_171     C
172  TEST_172     C
173  TEST_173     B
174  TEST_174     B

[175 rows x 2 columns]

In [159]:
df['class'].value_counts()

B    85
A    51
C    39
Name: class, dtype: int64

# 0.9719