In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm

In [2]:
train = pd.read_csv("data/train.csv")
test = pd.read_csv("data/test.csv")
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 262 entries, 0 to 261
Data columns (total 21 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      262 non-null    object
 1   father  262 non-null    int64
 2   mother  262 non-null    int64
 3   gender  262 non-null    int64
 4   trait   262 non-null    int64
 5   SNP_01  262 non-null    object
 6   SNP_02  262 non-null    object
 7   SNP_03  262 non-null    object
 8   SNP_04  262 non-null    object
 9   SNP_05  262 non-null    object
 10  SNP_06  262 non-null    object
 11  SNP_07  262 non-null    object
 12  SNP_08  262 non-null    object
 13  SNP_09  262 non-null    object
 14  SNP_10  262 non-null    object
 15  SNP_11  262 non-null    object
 16  SNP_12  262 non-null    object
 17  SNP_13  262 non-null    object
 18  SNP_14  262 non-null    object
 19  SNP_15  262 non-null    object
 20  class   262 non-null    object
dtypes: int64(4), object(17)
memory usage: 43.1+ KB

In [3]:
df = pd.concat([train, test], ignore_index=True)
df

,id,father,mother,gender,trait,SNP_01,SNP_02,SNP_03,SNP_04,SNP_05,...,SNP_07,SNP_08,SNP_09,SNP_10,SNP_11,SNP_12,SNP_13,SNP_14,SNP_15,class
0,TRAIN_000,0,0,0,2,G G,A G,A A,G A,C A,...,A A,G G,A A,G G,A G,A A,A A,A A,A A,B
1,TRAIN_001,0,0,0,2,A G,A G,C A,A A,A A,...,A A,G A,A A,A G,A A,G A,G G,A A,A A,C
2,TRAIN_002,0,0,0,2,G G,G G,A A,G A,C C,...,A A,G A,G A,A G,A A,A A,A A,A A,A A,B
3,TRAIN_003,0,0,0,1,A A,G G,A A,G A,A A,...,G G,A A,G G,A G,G G,G G,G G,A A,G G,A
4,TRAIN_004,0,0,0,2,G G,G G,C C,A A,C C,...,A A,A A,A A,G G,A A,A A,A G,A A,G A,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,TEST_170,0,0,0,2,A G,G G,C C,A A,C A,...,A A,G G,A A,G G,G G,A A,A A,A A,G A,NaN
433,TEST_171,0,0,0,2,G G,A A,A A,A A,C A,...,A A,A A,A A,A G,A A,A A,A G,A A,G A,NaN
434,TEST_172,0,0,0,2,G G,A A,A A,A A,C A,...,A A,A A,A A,G G,A G,A A,A G,A A,G G,NaN
435,TEST_173,0,0,0,2,A G,G G,C A,G A,C C,...,A A,G A,A A,G G,A G,A A,A A,A A,A A,NaN
436,TEST_174,0,0,0,2,G G,G G,C C,G A,C A,...,G A,G G,A A,G G,G G,A A,A A,A A,A A,NaN

In [4]:
df['trait'] = df['trait']-1
df.drop(columns=['father', 'mother', 'gender'], inplace=True)
df

,id,trait,SNP_01,SNP_02,SNP_03,SNP_04,SNP_05,SNP_06,SNP_07,SNP_08,SNP_09,SNP_10,SNP_11,SNP_12,SNP_13,SNP_14,SNP_15,class
0,TRAIN_000,1,G G,A G,A A,G A,C A,A A,A A,G G,A A,G G,A G,A A,A A,A A,A A,B
1,TRAIN_001,1,A G,A G,C A,A A,A A,A G,A A,G A,A A,A G,A A,G A,G G,A A,A A,C
2,TRAIN_002,1,G G,G G,A A,G A,C C,G G,A A,G A,G A,A G,A A,A A,A A,A A,A A,B
3,TRAIN_003,0,A A,G G,A A,G A,A A,G G,G G,A A,G G,A G,G G,G G,G G,A A,G G,A
4,TRAIN_004,1,G G,G G,C C,A A,C C,A A,A A,A A,A A,G G,A A,A A,A G,A A,G A,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,TEST_170,1,A G,G G,C C,A A,C A,A G,A A,G G,A A,G G,G G,A A,A A,A A,G A,NaN
433,TEST_171,1,G G,A A,A A,A A,C A,A G,A A,A A,A A,A G,A A,A A,A G,A A,G A,NaN
434,TEST_172,1,G G,A A,A A,A A,C A,A G,A A,A A,A A,G G,A G,A A,A G,A A,G G,NaN
435,TEST_173,1,A G,G G,C A,G A,C C,G G,A A,G A,A A,G G,A G,A A,A A,A A,A A,NaN
436,TEST_174,1,G G,G G,C C,G A,C A,A A,G A,G G,A A,G G,G G,A A,A A,A A,A A,NaN

In [5]:
for i in tqdm(range(1, 15+1)) :
    target = str(i) if i >= 10 else "0"+str(i)
    cols = sorted(df[f"SNP_{target}"].unique().tolist())
    df[f"SNP_{target}"] = df[f"SNP_{target}"].map(lambda x : 0 if x==cols[0] else (1 if x==cols[1] else 2))
df

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 2448.51it/s]

,id,trait,SNP_01,SNP_02,SNP_03,SNP_04,SNP_05,SNP_06,SNP_07,SNP_08,SNP_09,SNP_10,SNP_11,SNP_12,SNP_13,SNP_14,SNP_15,class
0,TRAIN_000,1,2,1,0,1,1,0,0,2,0,2,1,0,0,0,0,B
1,TRAIN_001,1,1,1,1,0,0,1,0,1,0,1,0,1,2,0,0,C
2,TRAIN_002,1,2,2,0,1,2,2,0,1,1,1,0,0,0,0,0,B
3,TRAIN_003,0,0,2,0,1,0,2,2,0,2,1,2,2,2,0,2,A
4,TRAIN_004,1,2,2,2,0,2,0,0,0,0,2,0,0,1,0,1,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,TEST_170,1,1,2,2,0,1,1,0,2,0,2,2,0,0,0,1,NaN
433,TEST_171,1,2,0,0,0,1,1,0,0,0,1,0,0,1,0,1,NaN
434,TEST_172,1,2,0,0,0,1,1,0,0,0,2,1,0,1,0,2,NaN
435,TEST_173,1,1,2,1,1,2,2,0,1,0,2,1,0,0,0,0,NaN
436,TEST_174,1,2,2,2,1,1,0,1,2,0,2,2,0,0,0,0,NaN

In [6]:
df['class_B'] = df['class'].map(lambda x : 1 if x=='B' else 0)
df['class_C'] = df['class'].map(lambda x : 1 if x=='C' else 0)
df['class'] = df['class'].map(lambda x : 0 if x == 'A' else (1 if x=='B' else (2 if x=='C' else 3)))

for i in range(1, 15+1) :
    target = str(i) if i >= 10 else "0"+str(i)
    target2 = df.groupby(f'SNP_{target}')['class_B', 'class_C'].sum()
    
    for j in range(3) :
        value = target2['class_B'] / (target2['class_B']+target2['class_C'])
        df[f"SNP_{target}_ratio"] = df[f"SNP_{target}"].map(lambda x : value[0] if x==0 else (value[1] if x==1 else value[2])).fillna(0)    

df

/tmp/ipykernel_935599/1331533363.py:7: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  target2 = df.groupby(f'SNP_{target}')['class_B', 'class_C'].sum()
/tmp/ipykernel_935599/1331533363.py:7: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  target2 = df.groupby(f'SNP_{target}')['class_B', 'class_C'].sum()
/tmp/ipykernel_935599/1331533363.py:7: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  target2 = df.groupby(f'SNP_{target}')['class_B', 'class_C'].sum()
/tmp/ipykernel_935599/1331533363.py:7: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  target2 = df.groupby(f'SNP_{target}')['class_B', 'class_C'].sum()
/tmp/ipykernel_935599/1331533363.py:7: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  target2 = df.groupby(f'SNP_{target}')['class_B', 'class_C'].sum()
/tmp/ipykernel_935599/1331533363.py:7: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  target2 = df.groupby(f'SNP_{target}')['class_B', 'class_C'].sum()
/tmp/ipykernel_935599/1331533363.py:7: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  target2 = df.groupby(f'SNP_{target}')['class_B', 'class_C'].sum()
/tmp/ipykernel_935599/1331533363.py:7: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  target2 = df.groupby(f'SNP_{target}')['class_B', 'class_C'].sum()
/tmp/ipykernel_935599/1331533363.py:7: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  target2 = df.groupby(f'SNP_{target}')['class_B', 'class_C'].sum()
/tmp/ipykernel_935599/1331533363.py:7: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  target2 = df.groupby(f'SNP_{target}')['class_B', 'class_C'].sum()
/tmp/ipykernel_935599/1331533363.py:7: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  target2 = df.groupby(f'SNP_{target}')['class_B', 'class_C'].sum()
/tmp/ipykernel_935599/1331533363.py:7: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  target2 = df.groupby(f'SNP_{target}')['class_B', 'class_C'].sum()
/tmp/ipykernel_935599/1331533363.py:7: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  target2 = df.groupby(f'SNP_{target}')['class_B', 'class_C'].sum()
/tmp/ipykernel_935599/1331533363.py:7: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  target2 = df.groupby(f'SNP_{target}')['class_B', 'class_C'].sum()
/tmp/ipykernel_935599/1331533363.py:7: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  target2 = df.groupby(f'SNP_{target}')['class_B', 'class_C'].sum()

,id,trait,SNP_01,SNP_02,SNP_03,SNP_04,SNP_05,SNP_06,SNP_07,SNP_08,...,SNP_06_ratio,SNP_07_ratio,SNP_08_ratio,SNP_09_ratio,SNP_10_ratio,SNP_11_ratio,SNP_12_ratio,SNP_13_ratio,SNP_14_ratio,SNP_15_ratio
0,TRAIN_000,1,2,1,0,1,1,0,0,2,...,0.540984,0.644172,0.822785,0.538462,0.743243,0.662651,0.577778,0.826923,0.655172,0.689320
1,TRAIN_001,1,1,1,1,0,0,1,0,1,...,0.598039,0.644172,0.482353,0.538462,0.117647,0.421687,0.603774,0.367347,0.655172,0.689320
2,TRAIN_002,1,2,2,0,1,2,2,0,1,...,0.666667,0.644172,0.482353,0.956522,0.117647,0.421687,0.577778,0.826923,0.655172,0.689320
3,TRAIN_003,0,0,2,0,1,0,2,2,0,...,0.666667,0.000000,0.275862,1.000000,0.117647,0.888889,0.800000,0.367347,0.655172,0.272727
4,TRAIN_004,1,2,2,2,0,2,0,0,0,...,0.540984,0.644172,0.275862,0.538462,0.743243,0.421687,0.577778,0.576087,0.655172,0.506329
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,TEST_170,1,1,2,2,0,1,1,0,2,...,0.598039,0.644172,0.822785,0.538462,0.743243,0.888889,0.577778,0.826923,0.655172,0.506329
433,TEST_171,1,2,0,0,0,1,1,0,0,...,0.598039,0.644172,0.275862,0.538462,0.117647,0.421687,0.577778,0.576087,0.655172,0.506329
434,TEST_172,1,2,0,0,0,1,1,0,0,...,0.598039,0.644172,0.275862,0.538462,0.743243,0.662651,0.577778,0.576087,0.655172,0.272727
435,TEST_173,1,1,2,1,1,2,2,0,1,...,0.666667,0.644172,0.482353,0.538462,0.743243,0.662651,0.577778,0.826923,0.655172,0.689320
436,TEST_174,1,2,2,2,1,1,0,1,2,...,0.540984,0.300000,0.822785,0.538462,0.743243,0.888889,0.577778,0.826923,0.655172,0.689320

In [7]:
target2

        class_B  class_C
SNP_15
0            71       32
1            40       39
2             3        8

In [12]:
target = df.groupby('trait')['class_B', 'class_C'].sum()
target2 = (target['class_B'] / (target['class_B']+target['class_C'])).fillna(0)
target2

/tmp/ipykernel_935599/3845121111.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  target = df.groupby('trait')['class_B', 'class_C'].sum()

trait
0    0.000000
1    0.590674
dtype: float64

In [14]:
df['trait_ratio'] = df[f"trait"].map(lambda x : target2[0] if x==0 else target2[1])
df

,id,trait,SNP_01,SNP_02,SNP_03,SNP_04,SNP_05,SNP_06,SNP_07,SNP_08,...,SNP_07_ratio,SNP_08_ratio,SNP_09_ratio,SNP_10_ratio,SNP_11_ratio,SNP_12_ratio,SNP_13_ratio,SNP_14_ratio,SNP_15_ratio,trait_ratio
0,TRAIN_000,1,2,1,0,1,1,0,0,2,...,0.644172,0.822785,0.538462,0.743243,0.662651,0.577778,0.826923,0.655172,0.689320,0.590674
1,TRAIN_001,1,1,1,1,0,0,1,0,1,...,0.644172,0.482353,0.538462,0.117647,0.421687,0.603774,0.367347,0.655172,0.689320,0.590674
2,TRAIN_002,1,2,2,0,1,2,2,0,1,...,0.644172,0.482353,0.956522,0.117647,0.421687,0.577778,0.826923,0.655172,0.689320,0.590674
3,TRAIN_003,0,0,2,0,1,0,2,2,0,...,0.000000,0.275862,1.000000,0.117647,0.888889,0.800000,0.367347,0.655172,0.272727,0.000000
4,TRAIN_004,1,2,2,2,0,2,0,0,0,...,0.644172,0.275862,0.538462,0.743243,0.421687,0.577778,0.576087,0.655172,0.506329,0.590674
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,TEST_170,1,1,2,2,0,1,1,0,2,...,0.644172,0.822785,0.538462,0.743243,0.888889,0.577778,0.826923,0.655172,0.506329,0.590674
433,TEST_171,1,2,0,0,0,1,1,0,0,...,0.644172,0.275862,0.538462,0.117647,0.421687,0.577778,0.576087,0.655172,0.506329,0.590674
434,TEST_172,1,2,0,0,0,1,1,0,0,...,0.644172,0.275862,0.538462,0.743243,0.662651,0.577778,0.576087,0.655172,0.272727,0.590674
435,TEST_173,1,1,2,1,1,2,2,0,1,...,0.644172,0.482353,0.538462,0.743243,0.662651,0.577778,0.826923,0.655172,0.689320,0.590674
436,TEST_174,1,2,2,2,1,1,0,1,2,...,0.300000,0.822785,0.538462,0.743243,0.888889,0.577778,0.826923,0.655172,0.689320,0.590674

In [15]:
train2 = df[df['id'].str.contains('TRAIN')].copy()
train2['class'].value_counts()

1    114
2     79
0     69
Name: class, dtype: int64

In [16]:
test2 = df[df['id'].str.contains('TEST')].copy()
test2

,id,trait,SNP_01,SNP_02,SNP_03,SNP_04,SNP_05,SNP_06,SNP_07,SNP_08,...,SNP_07_ratio,SNP_08_ratio,SNP_09_ratio,SNP_10_ratio,SNP_11_ratio,SNP_12_ratio,SNP_13_ratio,SNP_14_ratio,SNP_15_ratio,trait_ratio
262,TEST_000,0,1,2,0,1,0,1,2,1,...,0.000000,0.482353,0.956522,0.117647,0.662651,0.603774,0.367347,0.000000,0.506329,0.000000
263,TEST_001,1,2,1,2,2,2,0,0,0,...,0.644172,0.275862,0.538462,0.743243,0.662651,0.577778,0.826923,0.655172,0.689320,0.590674
264,TEST_002,1,2,1,0,0,1,1,0,0,...,0.644172,0.275862,0.538462,0.117647,0.421687,0.603774,0.367347,0.655172,0.272727,0.590674
265,TEST_003,1,2,1,1,0,2,0,0,0,...,0.644172,0.275862,0.538462,0.743243,0.421687,0.603774,0.576087,0.655172,0.689320,0.590674
266,TEST_004,0,0,2,0,2,0,2,2,0,...,0.000000,0.275862,1.000000,0.117647,0.888889,0.603774,0.367347,0.655172,0.272727,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,TEST_170,1,1,2,2,0,1,1,0,2,...,0.644172,0.822785,0.538462,0.743243,0.888889,0.577778,0.826923,0.655172,0.506329,0.590674
433,TEST_171,1,2,0,0,0,1,1,0,0,...,0.644172,0.275862,0.538462,0.117647,0.421687,0.577778,0.576087,0.655172,0.506329,0.590674
434,TEST_172,1,2,0,0,0,1,1,0,0,...,0.644172,0.275862,0.538462,0.743243,0.662651,0.577778,0.576087,0.655172,0.272727,0.590674
435,TEST_173,1,1,2,1,1,2,2,0,1,...,0.644172,0.482353,0.538462,0.743243,0.662651,0.577778,0.826923,0.655172,0.689320,0.590674
436,TEST_174,1,2,2,2,1,1,0,1,2,...,0.300000,0.822785,0.538462,0.743243,0.888889,0.577778,0.826923,0.655172,0.689320,0.590674

In [17]:
train2.drop(columns=['class_B', 'class_C'], inplace=True)
test2.drop(columns=['class_B', 'class_C'], inplace=True)

In [18]:
train2.to_csv("./data/df_train5.csv", index=False)
test2.to_csv("./data/df_test5.csv", index=False)

In [37]:
import warnings
warnings.filterwarnings(action='ignore')

import os
import gc
import math
import random
import pickle
import pandas as pd
import numpy as np
from tqdm.auto import tqdm

from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split, StratifiedKFold

from xgboost import XGBClassifier
from imblearn.over_sampling import SMOTE

In [38]:
from xgboost import XGBClassifier, XGBRegressor
from imblearn.over_sampling import SMOTE

xgb_params = {
    'booster': 'gbtree',
    'grow_policy': 'lossguide',
    'max_depth': 0,
    'learning_rate': 0.4,
    'n_estimators': 30,
    'reg_lambda': 100,
    'subsample': 0.9,
    'num_parallel_tree': 1,
    # 'rate_drop': 0.3
}

In [39]:
train = pd.read_csv("./data/df_train5.csv")
test = pd.read_csv("./data/df_test5.csv")
train.shape, test.shape

((262, 34), (175, 34))

In [40]:
train = train[train['class']!=0].copy().reset_index(drop=True).drop(columns=['trait'])
test.drop(columns=['trait'], inplace=True)
train['class'] = train['class'] - 1
train['class'].value_counts()

0    114
1     79
Name: class, dtype: int64

In [41]:
train.to_csv("./data/df_train6.csv", index=False)
test.to_csv("./data/df_test6.csv", index=False)

In [30]:
def calc_f1_score(y_hat, data):
    y_true = data.get_label()
    y_hat = np.round(y_hat)
    return 'f1', f1_score(y_true, y_hat, average="macro")

In [31]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [36]:
random_seed = 0

y = train['class'].values
X = train.drop(['id', 'class'], axis=1).to_numpy()
X_test = test.drop(['id', 'class'], axis=1).to_numpy()

skf = StratifiedKFold(n_splits=2, shuffle=True, random_state=random_seed)

oof_val_preds = np.zeros((X.shape[0], 2))
oof_val_preds2 = np.zeros((X.shape[0], 2))
oof_val_preds3 = np.zeros((X.shape[0], 2))
oof_test_preds = np.zeros((X_test.shape[0], 2))

# OOF
for fold, (train_idx, valid_idx) in enumerate(skf.split(X, y)):

    print('#'*30, f'Fold [{fold+1}/{skf.n_splits}]', '#'*30)

    # train, valid data 설정
    X_train, y_train = X[train_idx], y[train_idx]
    X_valid, y_valid = X[valid_idx], y[valid_idx]
    
    # strategy = {0:114, 1:114}
    strategy = 'auto'
    smote = SMOTE(random_state=random_seed, k_neighbors=4, sampling_strategy=strategy)
    X_train, y_train = smote.fit_resample(X_train, y_train)

    # 불균형 데이터 가중치 조정 값 => 음성(0) 타깃값 개수 / 양성(1) 타깃값 개수
    _, counts = np.unique(np.array(y_train), return_counts=True)
    scale_weight = counts[0] / counts[1]

    # XGBoost 모델 훈련
    xgb_model = XGBClassifier(
        **xgb_params,
        tree_method='gpu_hist',
        predictor='gpu_predictor',
        random_state=random_seed,
        n_jobs=-1
    )
    
    rf = RandomForestClassifier()
    lr = LogisticRegression(C=100)
    
    xgb_model.fit(X_train, y_train, eval_set=[(X_valid, y_valid)], eval_metric=calc_f1_score, verbose=True)
    rf.fit(X_train, y_train)
    lr.fit(X_train, y_train)

    oof_test_preds += xgb_model.predict_proba(X_test) / skf.n_splits
    oof_val_preds[valid_idx] += xgb_model.predict_proba(X_valid)
    oof_val_preds2[valid_idx] += rf.predict_proba(X_valid)
    oof_val_preds3[valid_idx] += lr.predict_proba(X_valid)
    
    #model save
    # xgb_model.save_model(f'./models/new_xgb_{skf.n_splits}_{fold}.json')
    del [[X_train, y_train, X_valid, y_valid, xgb_model]]
    gc.collect()

#     model score check
preds = np.argmax(oof_val_preds, axis=1)
preds2 = np.argmax(oof_val_preds2, axis=1)
preds3 = np.argmax(oof_val_preds3, axis=1)
print(f1_score(y, preds, average="macro"))
print(f1_score(y, preds2, average="macro"))
print(f1_score(y, preds3, average="macro"))

# # save OOF test preds
# np.save(f'./results/new_{skf.n_splits}_oof_test_preds.npy', oof_test_preds[:, 1])

############################## Fold [1/2] ##############################
[0]	validation_0-logloss:0.67523	validation_0-f1:0.86223
[1]	validation_0-logloss:0.65673	validation_0-f1:0.87326
[2]	validation_0-logloss:0.63904	validation_0-f1:0.82332
[3]	validation_0-logloss:0.62266	validation_0-f1:0.82332
[4]	validation_0-logloss:0.61270	validation_0-f1:0.82332
[5]	validation_0-logloss:0.59845	validation_0-f1:0.82332
[6]	validation_0-logloss:0.58623	validation_0-f1:0.82332
[7]	validation_0-logloss:0.57371	validation_0-f1:0.81331
[8]	validation_0-logloss:0.56512	validation_0-f1:0.81331
[9]	validation_0-logloss:0.55435	validation_0-f1:0.80123
[10]	validation_0-logloss:0.54469	validation_0-f1:0.80620
[11]	validation_0-logloss:0.53756	validation_0-f1:0.80620
[12]	validation_0-logloss:0.52835	validation_0-f1:0.79622
[13]	validation_0-logloss:0.52146	validation_0-f1:0.79622
[14]	validation_0-logloss:0.51539	validation_0-f1:0.87021
[15]	validation_0-logloss:0.51022	validation_0-f1:0.87021
[16]	validation_0-logloss:0.50183	validation_0-f1:0.79622
[17]	validation_0-logloss:0.49703	validation_0-f1:0.85724
[18]	validation_0-logloss:0.49033	validation_0-f1:0.79622
[19]	validation_0-logloss:0.48507	validation_0-f1:0.85724
[20]	validation_0-logloss:0.48042	validation_0-f1:0.88156
[21]	validation_0-logloss:0.47405	validation_0-f1:0.85724
[22]	validation_0-logloss:0.47014	validation_0-f1:0.88156
[23]	validation_0-logloss:0.46227	validation_0-f1:0.88156
[24]	validation_0-logloss:0.45588	validation_0-f1:0.88156
[25]	validation_0-logloss:0.45023	validation_0-f1:0.88156
[26]	validation_0-logloss:0.44629	validation_0-f1:0.88156
[27]	validation_0-logloss:0.44017	validation_0-f1:0.88156
[28]	validation_0-logloss:0.43674	validation_0-f1:0.88156
[29]	validation_0-logloss:0.43199	validation_0-f1:0.87021
############################## Fold [2/2] ##############################
[0]	validation_0-logloss:0.67447	validation_0-f1:0.80399
[1]	validation_0-logloss:0.65996	validation_0-f1:0.81849
[2]	validation_0-logloss:0.64434	validation_0-f1:0.83984
[3]	validation_0-logloss:0.63059	validation_0-f1:0.85000
[4]	validation_0-logloss:0.61790	validation_0-f1:0.85000
[5]	validation_0-logloss:0.60313	validation_0-f1:0.86020
[6]	validation_0-logloss:0.59238	validation_0-f1:0.83984
[7]	validation_0-logloss:0.58115	validation_0-f1:0.86020
[8]	validation_0-logloss:0.56958	validation_0-f1:0.83984
[9]	validation_0-logloss:0.55691	validation_0-f1:0.87045
[10]	validation_0-logloss:0.54691	validation_0-f1:0.87045
[11]	validation_0-logloss:0.53649	validation_0-f1:0.91363
[12]	validation_0-logloss:0.52740	validation_0-f1:0.90321
[13]	validation_0-logloss:0.51783	validation_0-f1:0.91363
[14]	validation_0-logloss:0.50928	validation_0-f1:0.88171
[15]	validation_0-logloss:0.50202	validation_0-f1:0.87045
[16]	validation_0-logloss:0.49447	validation_0-f1:0.87045
[17]	validation_0-logloss:0.48667	validation_0-f1:0.88171
[18]	validation_0-logloss:0.48003	validation_0-f1:0.87045
[19]	validation_0-logloss:0.47255	validation_0-f1:0.87045
[20]	validation_0-logloss:0.46587	validation_0-f1:0.87966
[21]	validation_0-logloss:0.46021	validation_0-f1:0.90243
[22]	validation_0-logloss:0.45411	validation_0-f1:0.90243
[23]	validation_0-logloss:0.44931	validation_0-f1:0.89204
[24]	validation_0-logloss:0.44485	validation_0-f1:0.89204
[25]	validation_0-logloss:0.44042	validation_0-f1:0.89204
[26]	validation_0-logloss:0.43516	validation_0-f1:0.89204
[27]	validation_0-logloss:0.43028	validation_0-f1:0.89204
[28]	validation_0-logloss:0.42557	validation_0-f1:0.88075
[29]	validation_0-logloss:0.42031	validation_0-f1:0.88075
0.8754803781312239
0.9407066052227342
0.9146017699115043

In [28]:
random_seed = 0

y = train['class'].values
X = train.drop(['id', 'class', 'class_B', 'class_C'], axis=1).to_numpy()
X_test = test.drop(['id', 'class', 'class_B', 'class_C'], axis=1).to_numpy()

skf = StratifiedKFold(n_splits=2, shuffle=True, random_state=random_seed)

oof_val_preds = np.zeros((X.shape[0], 3))
oof_val_preds2 = np.zeros((X.shape[0], 3))
oof_val_preds3 = np.zeros((X.shape[0], 3))
oof_test_preds = np.zeros((X_test.shape[0], 3))

# OOF
for fold, (train_idx, valid_idx) in enumerate(skf.split(X, y)):

    # print('#'*30, f'Fold [{fold+1}/{skf.n_splits}]', '#'*30)

    # train, valid data 설정
    X_train, y_train = X[train_idx], y[train_idx]
    X_valid, y_valid = X[valid_idx], y[valid_idx]
    
    strategy = {0:500, 1:500, 2:500}
    smote = SMOTE(random_state=random_seed, k_neighbors=6, sampling_strategy=strategy)
    X_train, y_train = smote.fit_resample(X_train, y_train)

    # 불균형 데이터 가중치 조정 값 => 음성(0) 타깃값 개수 / 양성(1) 타깃값 개수
    _, counts = np.unique(np.array(y_train), return_counts=True)
    scale_weight = counts[0] / counts[1]

    # XGBoost 모델 훈련
    xgb_model = XGBClassifier(
        **xgb_params,
        tree_method='gpu_hist',
        predictor='gpu_predictor',
        random_state=random_seed,
        n_jobs=-1
    )
    
    rf = RandomForestClassifier()
    lr = LogisticRegression(C=100)
    
    xgb_model.fit(X_train, y_train, eval_set=[(X_valid, y_valid)], eval_metric=calc_f1_score, verbose=False)
    rf.fit(X_train, y_train)
    lr.fit(X_train, y_train)

    oof_test_preds += xgb_model.predict_proba(X_test) / skf.n_splits
    oof_val_preds[valid_idx] += xgb_model.predict_proba(X_valid)
    oof_val_preds2[valid_idx] += rf.predict_proba(X_valid)
    oof_val_preds3[valid_idx] += lr.predict_proba(X_valid)
    
    #model save
    # xgb_model.save_model(f'./models/new_xgb_{skf.n_splits}_{fold}.json')
    del [[X_train, y_train, X_valid, y_valid, xgb_model]]
    gc.collect()

#     model score check
preds = np.argmax(oof_val_preds, axis=1)
preds2 = np.argmax(oof_val_preds2, axis=1)
preds3 = np.argmax(oof_val_preds3, axis=1)
print(f1_score(y, preds, average="macro"))
print(f1_score(y, preds2, average="macro"))
print(f1_score(y, preds3, average="macro"))

# # save OOF test preds
# np.save(f'./results/new_{skf.n_splits}_oof_test_preds.npy', oof_test_preds[:, 1])

KeyError: "['class_B', 'class_C'] not found in axis"

In [40]:
# XGBoost 모델 훈련
xgb_model = XGBClassifier(
    **xgb_params,
    tree_method='gpu_hist',
    predictor='gpu_predictor',
    random_state=random_seed,
    n_jobs=-1
)

smote = SMOTE(random_state=random_seed, sample_strategy=0.9)
X_train, y_train = smote.fit_resample(X, y)
xgb_model.fit(X_train, y_train)
preds = xgb_model.predict(X)
score = f1_score(y, preds, average='macro')
score

0.9713117800074321

In [87]:
xgb_params = {
    'booster': 'gbtree',
    'grow_policy': 'lossguide',
    'max_depth': 0,
    'learning_rate': 0.4,
    'n_estimators': 30,
    'reg_lambda': 100,
    'subsample': 0.9,
    'num_parallel_tree': 3,
    # 'rate_drop': 0.3
}

# XGBoost 모델 훈련
xgb_model = XGBClassifier(
    **xgb_params,
    tree_method='gpu_hist',
    predictor='gpu_predictor',
    random_state=random_seed,
    n_jobs=-1
)
strategy = {0:6900, 1:11400, 2:7900}
smote = SMOTE(random_state=random_seed, k_neighbors=7, sampling_strategy=strategy)
X_train, y_train = smote.fit_resample(X, y)
xgb_model.fit(X_train, y_train)
preds = xgb_model.predict(X)
score = f1_score(y, preds, average='macro')
score

0.9892637610213334

In [91]:
xgb_params = {
    'booster': 'gbtree',
    'grow_policy': 'lossguide',
    'max_depth': 0,
    'learning_rate': 0.4,
    'n_estimators': 30,
    'reg_lambda': 100,
    'subsample': 0.9,
    'num_parallel_tree': 10,
    # 'rate_drop': 0.3
}

# XGBoost 모델 훈련
xgb_model = XGBClassifier(
    **xgb_params,
    tree_method='gpu_hist',
    predictor='gpu_predictor',
    random_state=random_seed,
    n_jobs=-1
)
strategy = {0:100000-2000, 1:100000, 2:100000-1000}
smote = SMOTE(random_state=random_seed, k_neighbors=6, sampling_strategy=strategy)
X_train, y_train = smote.fit_resample(X, y)
xgb_model.fit(X_train, y_train)
preds = xgb_model.predict(X)
score = f1_score(y, preds, average='macro')
score

0.9964212536737779

In [94]:
xgb_params = {
    'booster': 'dart',
    'grow_policy': 'lossguide',
    'max_depth': 0,
    'learning_rate': 0.4,
    'n_estimators': 100,
    'reg_lambda': 100,
    'subsample': 0.3,
    'num_parallel_tree': 3,
    'rate_drop': 0.3
}

# XGBoost 모델 훈련
xgb_model = XGBClassifier(
    **xgb_params,
    tree_method='gpu_hist',
    predictor='gpu_predictor',
    random_state=random_seed,
    n_jobs=-1
)
strategy = {0:100000-2000, 1:100000, 2:100000-1000}
smote = SMOTE(random_state=random_seed, k_neighbors=6, sampling_strategy=strategy)
X_train, y_train = smote.fit_resample(X, y)
xgb_model.fit(X_train, y_train)
preds = xgb_model.predict(X)
score = f1_score(y, preds, average='macro')
score

0.9783922973578146

In [69]:
preds = xgb_model.predict(X_test)

In [17]:
oof_test_preds

array([[0.88424724, 0.0558494 , 0.05990337],
       [0.06988881, 0.82047993, 0.10963123],
       [0.05462112, 0.0705538 , 0.87482509],
       [0.04198926, 0.50111438, 0.45689636],
       [0.88433608, 0.05575443, 0.05990949],
       [0.05097254, 0.49671076, 0.45231673],
       [0.06751075, 0.09407424, 0.838415  ],
       [0.06790101, 0.72782215, 0.20427684],
       [0.77220559, 0.04806118, 0.17973325],
       [0.88493034, 0.05511923, 0.05995045],
       [0.06494478, 0.0858714 , 0.84918383],
       [0.07185402, 0.83379546, 0.09435049],
       [0.13122553, 0.54300578, 0.32576874],
       [0.88493034, 0.05511923, 0.05995045],
       [0.042549  , 0.62723175, 0.33021922],
       [0.05250299, 0.78947887, 0.15801816],
       [0.88493034, 0.05511923, 0.05995045],
       [0.05340891, 0.70687547, 0.23971561],
       [0.05513544, 0.87260893, 0.07225569],
       [0.09397346, 0.35893655, 0.54709002],
       [0.05253508, 0.85453731, 0.09292764],
       [0.17136051, 0.48003507, 0.34860441],
       [0.06843503, 0.73466289, 0.19690207],
       [0.88493034, 0.05511923, 0.05995045],
       [0.0660043 , 0.84777001, 0.08622571],
       [0.0841359 , 0.67650557, 0.23935852],
       [0.0616597 , 0.74092442, 0.19741589],
       [0.88493034, 0.05511923, 0.05995045],
       [0.88226447, 0.05796884, 0.0597667 ],
       [0.08723538, 0.79851732, 0.11424728],
       [0.88424724, 0.0558494 , 0.05990337],
       [0.88424724, 0.0558494 , 0.05990337],
       [0.05164293, 0.79302779, 0.1553293 ],
       [0.08105419, 0.26423395, 0.65471187],
       [0.88433608, 0.05575443, 0.05990949],
       [0.07517156, 0.64459008, 0.28023837],
       [0.07112029, 0.09749444, 0.83138525],
       [0.05036547, 0.79705322, 0.1525813 ],
       [0.05149003, 0.75649178, 0.19201823],
       [0.07880466, 0.15004718, 0.77114815],
       [0.88493034, 0.05511923, 0.05995045],
       [0.06846522, 0.83005607, 0.10147867],
       [0.06434774, 0.17591907, 0.7597332 ],
       [0.08723538, 0.79851732, 0.11424728],
       [0.04136292, 0.6689046 , 0.28973247],
       [0.05280739, 0.65345266, 0.29373996],
       [0.13951734, 0.60370964, 0.25677307],
       [0.0630843 , 0.26717161, 0.6697441 ],
       [0.05394469, 0.74942607, 0.19662918],
       [0.04313888, 0.26334102, 0.6935201 ],
       [0.88281184, 0.05738373, 0.05980442],
       [0.06917454, 0.84005654, 0.0907689 ],
       [0.84678227, 0.09583743, 0.0573803 ],
       [0.05244691, 0.79535559, 0.15219749],
       [0.0491241 , 0.80865908, 0.14221682],
       [0.06317388, 0.74102518, 0.19580096],
       [0.06547462, 0.13098306, 0.80354238],
       [0.88410076, 0.05600594, 0.05989327],
       [0.07123315, 0.82976317, 0.09900367],
       [0.07692907, 0.14355766, 0.7795133 ],
       [0.88069433, 0.05964402, 0.05966164],
       [0.05104046, 0.83125481, 0.11770474],
       [0.05563049, 0.07999911, 0.86437035],
       [0.05576696, 0.07777716, 0.86645585],
       [0.09346166, 0.30403344, 0.60250488],
       [0.79324096, 0.15294965, 0.05380938],
       [0.22082628, 0.491427  , 0.28774671],
       [0.88493034, 0.05511923, 0.05995045],
       [0.88493034, 0.05511923, 0.05995045],
       [0.04772163, 0.78574422, 0.16653418],
       [0.0590535 , 0.85757855, 0.08336799],
       [0.05305799, 0.86167511, 0.08526691],
       [0.88281184, 0.05738373, 0.05980442],
       [0.88428566, 0.05580834, 0.05990602],
       [0.06415712, 0.09740556, 0.83843735],
       [0.06289051, 0.73811772, 0.19899175],
       [0.05405816, 0.07742056, 0.8685213 ],
       [0.0503838 , 0.79730541, 0.15231077],
       [0.09658566, 0.77661967, 0.12679468],
       [0.0685649 , 0.82751161, 0.10392347],
       [0.11180188, 0.20473993, 0.68345815],
       [0.0473908 , 0.77996433, 0.17264485],
       [0.88493034, 0.05511923, 0.05995045],
       [0.0578489 , 0.74594456, 0.19620651],
       [0.18508805, 0.53123456, 0.28367738],
       [0.09658566, 0.77661967, 0.12679468],
       [0.05513544, 0.87260893, 0.07225569],
       [0.05143606, 0.84721559, 0.10134836],
       [0.06491331, 0.1741051 , 0.76098162],
       [0.88281184, 0.05738373, 0.05980442],
       [0.11934115, 0.71345928, 0.16719957],
       [0.06396857, 0.78450146, 0.15152996],
       [0.04097   , 0.31950232, 0.63952771],
       [0.06177897, 0.85740858, 0.08081246],
       [0.0538759 , 0.87555206, 0.07057208],
       [0.07186356, 0.10603286, 0.82210359],
       [0.88281184, 0.05738373, 0.05980442],
       [0.04538787, 0.67987862, 0.27473351],
       [0.88493034, 0.05511923, 0.05995045],
       [0.0681108 , 0.16900585, 0.76288339],
       [0.88428566, 0.05580834, 0.05990602],
       [0.08999979, 0.79229754, 0.11770266],
       [0.05266976, 0.78526771, 0.1620625 ],
       [0.1030912 , 0.15681993, 0.74008885],
       [0.88424724, 0.0558494 , 0.05990337],
       [0.88281184, 0.05738373, 0.05980442],
       [0.06893872, 0.14989442, 0.78116685],
       [0.05547225, 0.64967313, 0.29485463],
       [0.88493034, 0.05511923, 0.05995045],
       [0.06416468, 0.79206103, 0.14377426],
       [0.06630293, 0.0986752 , 0.83502188],
       [0.09128411, 0.77939758, 0.12931827],
       [0.0538759 , 0.87555206, 0.07057208],
       [0.05104046, 0.83125481, 0.11770474],
       [0.05868932, 0.76972055, 0.17159012],
       [0.88493034, 0.05511923, 0.05995045],
       [0.88493034, 0.05511923, 0.05995045],
       [0.07765163, 0.21223991, 0.71010846],
       [0.04489008, 0.74013358, 0.21497633],
       [0.04269282, 0.47266586, 0.48464134],
       [0.88281184, 0.05738373, 0.05980442],
       [0.0538759 , 0.87555206, 0.07057208],
       [0.06547732, 0.68894005, 0.24558264],
       [0.11147236, 0.32821763, 0.56031004],
       [0.08614483, 0.11514168, 0.79871345],
       [0.07062656, 0.8313086 , 0.09806483],
       [0.10858436, 0.57720527, 0.31421036],
       [0.06347491, 0.77774748, 0.15877761],
       [0.88493034, 0.05511923, 0.05995045],
       [0.0523439 , 0.79377788, 0.15387825],
       [0.88298255, 0.05720128, 0.05981619],
       [0.88281184, 0.05738373, 0.05980442],
       [0.08224689, 0.67643812, 0.24131498],
       [0.05039275, 0.79745722, 0.15215003],
       [0.05564411, 0.69423932, 0.2501166 ],
       [0.0564567 , 0.08873706, 0.85480624],
       [0.88493034, 0.05511923, 0.05995045],
       [0.88493034, 0.05511923, 0.05995045],
       [0.05793736, 0.6785661 , 0.26349652],
       [0.78186223, 0.1650921 , 0.05304563],
       [0.87039858, 0.0655023 , 0.0640991 ],
       [0.88493034, 0.05511923, 0.05995045],
       [0.06661178, 0.09493377, 0.83845451],
       [0.0538759 , 0.87555206, 0.07057208],
       [0.05825561, 0.7632986 , 0.17844578],
       [0.05792582, 0.6999366 , 0.24213763],
       [0.88428566, 0.05580834, 0.05990602],
       [0.05896407, 0.75685903, 0.18417691],
       [0.04432621, 0.26648977, 0.68918401],
       [0.88281184, 0.05738373, 0.05980442],
       [0.88493034, 0.05511923, 0.05995045],
       [0.08264007, 0.79684991, 0.12051   ],
       [0.88428566, 0.05580834, 0.05990602],
       [0.06917454, 0.84005654, 0.0907689 ],
       [0.05513544, 0.87260893, 0.07225569],
       [0.88493034, 0.05511923, 0.05995045],
       [0.88493034, 0.05511923, 0.05995045],
       [0.05363389, 0.8714461 , 0.07491999],
       [0.04456626, 0.23918015, 0.71625361],
       [0.88424724, 0.0558494 , 0.05990337],
       [0.05326019, 0.87699074, 0.06974908],
       [0.10617777, 0.18613136, 0.70769089],
       [0.07021191, 0.52072351, 0.40906456],
       [0.0538759 , 0.87555206, 0.07057208],
       [0.88493034, 0.05511923, 0.05995045],
       [0.88433608, 0.05575443, 0.05990949],
       [0.05430917, 0.07324355, 0.87244722],
       [0.07070329, 0.77607828, 0.15321844],
       [0.04677174, 0.6755245 , 0.27770378],
       [0.88493034, 0.05511923, 0.05995045],
       [0.05626927, 0.75186563, 0.19186509],
       [0.05426201, 0.07405703, 0.87168092],
       [0.05440084, 0.24084787, 0.70475128],
       [0.0538759 , 0.87555206, 0.07057208],
       [0.09208787, 0.76149362, 0.14641853]])

In [71]:
# submit_pred = np.argmax(oof_test_preds, axis=1)
submit_pred = preds
submit_file = pd.read_csv("./data/sample_submission.csv")
submit_file['class'] = submit_pred
submit_file['class'] = submit_file['class'].map(lambda x : "A" if x==0 else ( "B" if x==1 else "C"))
submit_file

           id class
0    TEST_000     A
1    TEST_001     B
2    TEST_002     C
3    TEST_003     B
4    TEST_004     A
..        ...   ...
170  TEST_170     B
171  TEST_171     C
172  TEST_172     C
173  TEST_173     B
174  TEST_174     B

[175 rows x 2 columns]

In [72]:
submit_file['class'].value_counts()

B    84
A    51
C    40
Name: class, dtype: int64

In [29]:
submit_file.to_csv("submit.csv", index=False)